# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.1

clone:
  depth: full
pipelines:
  default:
    - step: 
        deployment: production
        script:
          - curl -sL https://deb.nodesource.com/setup_8.x | bash -
          - apt-get install -y nodejs
          - npm install
          - npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
     
